<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: 无法使用数据库
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: 无法使用数据库
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/index_menu_load.php?openitem=100
Error: 无法使用数据库
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/index_menu_load.php?openitem=100
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_sys_module` ORDER BY id DESC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/index_menu_load.php?openitem=100
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: 无法使用数据库
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2018-06-12 22:15:23
*/
?>
<?php  exit();
/*
Page: /MyProject/src/MyPhpCms/DedeCMS/dede/
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2018-06-12 22:15:23
*/
?>
